name: Continuous Integration
on:
  push:
  pull_request:
  schedule:
    - cron: '0 15 * * *'
jobs:
  build:
    name: HHVM ${{matrix.hhvm}} - ${{matrix.os}}
    strategy:
      # Run tests on all OS's and HHVM versions, even if one fails
      fail-fast: false
      matrix:
        os: [ ubuntu , macos ]
        hhvm:
          - '4.108'
          - latest
          - nightly
    runs-on: ${{matrix.os}}-latest
    steps:
      - uses: actions/checkout@v2
      - name: Alias master for Composer `dev-master` version resolution
        run: |
          if [ ! -e .git/refs/heads/master ]; then
            git branch master HEAD
          fi
      - uses: hhvm/actions/hack-lint-test@master
        with:
          hhvm: ${{matrix.hhvm}}
          skip_lint: true
